apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: asia-northeast1
  name: main
spec:
  template:
    metadata:
      name: main-${{ github.event.pull_request.number }}
    spec:
      containerConcurrency: 1
      containers:
      - image: ${{ secrets.GCP_ARTIFACTREG_URL }}/main:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
      serviceAccountName: 758927254506-compute@developer.gserviceaccount.com
      timeoutSeconds: 10
  traffic:
  - latestRevision: true
    percent: 1