name: Deploying GCP
on:
  push:
    branches:
      - main

jobs:
  GCPSetup:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: gcloud info
  
      - name: debuging
        run: |
          pwd
          ls -altr
      
      - name: Authentication to GCP Artifact Registry 
        run: |-
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t "${{ secrets.GCP_ARTIFACTREG_URL }}" ./app
          docker push "${{ secrets.GCP_ARTIFACTREG_URL }}"